unit MHELP;

interface

const

  hcBak                  = 38;
  hcCalc                 = 39;
  hcCalculator           = 4;
  hcCalk                 = 42;
  hcCancelBtn            = 33;
  hcChangeBak            = 40;
  hcDelVar               = 41;
  hcFCChDirDBox          = 35;
  hcFChangeDir           = 13;
  hcFDosShell            = 14;
  hcFExit                = 15;
  hcFile                 = 11;
  hcFOFileOpenDBox       = 29;
  hcFOFiles              = 31;
  hcFOName               = 30;
  hcFont                 = 49;
  hcFOOpenBtn            = 32;
  hcFOpen                = 12;
  hcHeaderEdit           = 46;
  hcList                 = 48;
  hcNew                  = 44;
  hcNoContext            = 0;
  hcOCColorsDBox         = 37;
  hcOColors              = 26;
  hcOld                  = 43;
  hcOMMouseDBox          = 36;
  hcOMouse               = 25;
  hcOpenBtn              = 34;
  hcOptions              = 24;
  hcORestoreDesktop      = 28;
  hcOSaveDesktop         = 27;
  hcPalette              = 6;
  hcPrint                = 5;
  hcPuzzle               = 3;
  hcRed                  = 47;
  hcSAbout               = 8;
  hcSCalculator          = 10;
  hcSPuzzle              = 9;
  hcSystem               = 7;
  hcVar                  = 45;
  hcViewer               = 2;
  hcWCascade             = 20;
  hcWClose               = 23;
  hcWindows              = 16;
  hcWNext                = 21;
  hcWPrevious            = 22;
  hcWSizeMove            = 17;
  hcWTile                = 19;
  hcWZoom                = 18;

implementation

end.
