unit MHELP1;

interface

const

  hcBak                  = 11;
  hcCalk                 = 4;
  hcCancelBtn            = 34;
  hcChangeBAK            = 7;
  hcDelVar               = 6;
  hcFCChDirDBox          = 36;
  hcFChangeDir           = 15;
  hcFExit                = 17;
  hcFile                 = 13;
  hcFOFileOpenDBox       = 30;
  hcFOFiles              = 32;
  hcFOName               = 31;
  hcFont                 = 3;
  hcFOOpenBtn            = 33;
  hcFOpen                = 14;
  hcHeaderEdit           = 10;
  hcList                 = 5;
  hcNew                  = 27;
  hcNoContext            = 0;
  hcOCColorsDBox         = 38;
  hcOColors              = 28;
  hcOld                  = 16;
  hcOMMouseDBox          = 37;
  hcOpenBtn              = 35;
  hcOptions              = 26;
  hcORestoreDesktop      = 29;
  hcRed                  = 9;
  hcSCalculator          = 12;
  hcVar                  = 8;
  hcVarNewIndex          = 43;
  hcVarNq                = 39;
  hcVarNTem              = 41;
  hcVarNv                = 40;
  hcVarSumma             = 42;
  hcViewer               = 2;
  hcWCascade             = 22;
  hcWClose               = 25;
  hcWindows              = 18;
  hcWNext                = 23;
  hcWPrevious            = 24;
  hcWSizeMove            = 19;
  hcWTile                = 21;
  hcWZoom                = 20;

implementation

end.
